name: Astrometry.net

on:
  workflow_dispatch:

jobs:
  build-on-linux-x64:
    name: Build on Linux x64
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download
        run: git clone --depth 1 --single-branch https://github.com/tiagohm/astrometry.net.git

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y libcairo2-dev libnetpbm10-dev netpbm libpng-dev libjpeg-dev zlib1g-dev libbz2-dev libcfitsio-dev

      - name: Make
        working-directory: astrometry.net
        run: make SYSTEM_GSL=no solver

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: astrometrynet-linux-x64
          path: |
            astrometry.net/solver/libastrometry.so
          retention-days: 7

  build-on-linux-arm64:
    name: Build on Linux arm64
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download
        run: git clone --depth 1 --single-branch https://github.com/tiagohm/astrometry.net.git

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y libcairo2-dev libnetpbm10-dev netpbm libpng-dev libjpeg-dev zlib1g-dev libbz2-dev libcfitsio-dev

      - name: Make
        working-directory: astrometry.net
        run: make SYSTEM_GSL=no solver

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: astrometrynet-linux-arm64
          path: |
            astrometry.net/solver/libastrometry.so
          retention-days: 7

  build-on-windows-x64:
    name: Build on Windows x64
    runs-on: windows-2025
    continue-on-error: false

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            git
            make
            mingw-w64-x86_64-cfitsio
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-libsystre
            mingw-w64-x86_64-libjpeg-turbo

      - name: Checkout
        uses: actions/checkout@v6

      - name: Download
        run: git clone --depth 1 --single-branch https://github.com/tiagohm/astrometry.net.git

      - name: Make
        working-directory: astrometry.net
        run: |
          set -euo pipefail

          common_make_args=(
            SYSTEM_GSL=no
            SHAREDLIB_SUFFIX=dll
            'SHAREDLIBFLAGS_DEF=-shared -Wl,--out-implib,libastrometry.dll.a -Wl,--no-undefined'
            PYTHON_SO_EXT=.pyd
            "LDLIBS_DEF=$(pkg-config --libs cfitsio)"
          )

          make solver libastrometry.dll "${common_make_args[@]}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: astrometrynet-win32-x64
          path: |
            astrometry.net/solver/libastrometry.dll
          retention-days: 7
