name: WCS

on:
  workflow_dispatch:

jobs:
  build-on-linux-x64:
    name: Build on Linux x64
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download
        run: wget https://www.atnf.csiro.au/computing/software/wcs/wcslib-releases/wcslib-8.6.tar.bz2 -O wcslib.tar.bz2

      - name: Unzip
        run: bzcat wcslib.tar.bz2 | tar pvxf -

      - name: Configure
        working-directory: wcslib-8.6
        run: ./configure --disable-fortran --disable-flex --disable-utils --without-cfitsio --without-pgplot

      - name: Make
        working-directory: wcslib-8.6
        run: make build

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: libwcs-linux-x64
          path: |
            wcslib-8.6/C/libwcs.so.8.6
          retention-days: 1

  build-on-windows-x64:
    name: Build on Windows x64
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install MinGW-w64
        run: sudo apt update && sudo apt install -y gcc-mingw-w64-x86-64-posix

      - name: Download
        run: wget https://www.atnf.csiro.au/computing/software/wcs/wcslib-releases/wcslib-8.6.tar.bz2 -O wcslib.tar.bz2

      - name: Unzip
        run: bzcat wcslib.tar.bz2 | tar pvxf -

      - name: Configure
        working-directory: wcslib-8.6
        run: CC=x86_64-w64-mingw32-gcc LDFLAGS=-static ./configure --host=x86_64-w64-mingw32 --disable-fortran --disable-flex --disable-utils --without-cfitsio --without-pgplot CFLAGS=-DNO_OLDNAMES

      - name: Make
        working-directory: wcslib-8.6
        run: make build

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: libwcs-win32-x64
          path: |
            wcslib-8.6/C/libwcs.dll.8.6
          retention-days: 1

  build-on-linux-arm64:
    name: Build on Linux ARM64
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download
        run: wget https://www.atnf.csiro.au/computing/software/wcs/wcslib-releases/wcslib-8.6.tar.bz2 -O wcslib.tar.bz2

      - name: Unzip
        run: bzcat wcslib.tar.bz2 | tar pvxf -

      - name: Configure
        working-directory: wcslib-8.6
        run: ./configure --disable-fortran --disable-flex --disable-utils --without-cfitsio --without-pgplot

      - name: Make
        working-directory: wcslib-8.6
        run: make build

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: libwcs-linux-arm64
          path: |
            wcslib-8.6/C/libwcs.so.8.6
          retention-days: 1
